# Generated by Django 2.1.7 on 2019-05-29 21:36

import dialog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('dialog', '0001_initial'), ('dialog', '0002_auto_20190221_1646'), ('dialog', '0003_auto_20190221_1647'), ('dialog', '0004_remove_chatrecord_key'), ('dialog', '0005_auto_20190221_2350'), ('dialog', '0006_chatrating_study'), ('dialog', '0007_auto_20190312_1455'), ('dialog', '0008_chatrecord_study_key'), ('dialog', '0009_chatrating_study_key'), ('dialog', '0010_study_name'), ('dialog', '0011_chatrecord_rating'), ('dialog', '0012_chatrating_contingency'), ('dialog', '0013_auto_20190403_1758'), ('dialog', '0014_auto_20190408_2059'), ('dialog', '0015_auto_20190419_1901'), ('dialog', '0016_chatrating_quality'), ('dialog', '0017_chatrating_empathetic'), ('dialog', '0018_auto_20190422_2023'), ('dialog', '0019_auto_20190422_2038'), ('dialog', '0020_auto_20190506_1541'), ('dialog', '0021_chatrating_mturk_user_id'), ('dialog', '0022_study_is_anonymized')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('chat_id', models.CharField(db_index=True, max_length=64)),
                ('timestamp', models.DateTimeField()),
                ('chatbot_id', models.CharField(max_length=16)),
                ('message', models.TextField()),
                ('message_history', dialog.models.JsonField()),
                ('response', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunSQL(
            sql='ALTER TABLE dialog_chatrecord CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci',
        ),
        migrations.RunSQL(
            sql='ALTER TABLE dialog_chatrecord CHANGE response response TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL',
        ),
        migrations.RunSQL(
            sql='ALTER TABLE dialog_chatrecord CHANGE message_history message_history TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL',
        ),
        migrations.RunSQL(
            sql='ALTER TABLE dialog_chatrecord CHANGE message message TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL',
        ),
        migrations.CreateModel(
            name='ChatRating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('chat_id', models.CharField(db_index=True, max_length=128)),
                ('timestamp', models.DateTimeField()),
                ('chatbot_id', models.CharField(max_length=128)),
                ('coherency', models.IntegerField(null=True)),
                ('fluency', models.IntegerField()),
                ('diversity', models.IntegerField()),
                ('comments', models.TextField(blank=True)),
                ('study_key', models.CharField(max_length=128)),
                ('contingency', models.IntegerField(default=1)),
                ('user_session_id', models.CharField(max_length=128)),
                ('mturk_code', models.CharField(max_length=128)),
                ('quality', models.IntegerField(default=0)),
                ('empathy', models.IntegerField(default=0)),
                ('mturk_user_id', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(blank=True, db_index=True, max_length=128, unique=True)),
                ('is_random_bot', models.BooleanField(blank=True, default=False)),
                ('bot_list', models.TextField(blank=True)),
                ('name', models.CharField(max_length=128)),
                ('is_mturk', models.BooleanField(blank=True, default=False)),
                ('is_anonymized', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'studies',
            },
        ),
        migrations.AddField(
            model_name='chatrecord',
            name='study_key',
            field=models.CharField(max_length=128),
        ),
        migrations.AddField(
            model_name='chatrecord',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatrecord',
            name='user_session_id',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='chatrecord',
            name='chat_id',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='chatrecord',
            name='chatbot_id',
            field=models.CharField(max_length=128),
        ),
    ]
